// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjxp9k_yN9ouFcru2SycmFs-pUW-lEOMM',
    appId: '1:153309351632:web:e9086e5ff07266602f98d5',
    messagingSenderId: '153309351632',
    projectId: 'todoappflutter-1cff8',
    authDomain: 'todoappflutter-1cff8.firebaseapp.com',
    storageBucket: 'todoappflutter-1cff8.appspot.com',
    measurementId: 'G-SSYTDN5RJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVIqVo6vs2if74U9Z7KPPRXQ-tbf_osLs',
    appId: '1:153309351632:android:d23052cbb4c0b2eb2f98d5',
    messagingSenderId: '153309351632',
    projectId: 'todoappflutter-1cff8',
    storageBucket: 'todoappflutter-1cff8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDglNzPbqZCZs9FL6K_fLQ9UyVeRVdlV0k',
    appId: '1:153309351632:ios:b36577f9dd057fc62f98d5',
    messagingSenderId: '153309351632',
    projectId: 'todoappflutter-1cff8',
    storageBucket: 'todoappflutter-1cff8.appspot.com',
    iosClientId: '153309351632-6mfv424escs6a99vkc3h65rtdrnmdosv.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDglNzPbqZCZs9FL6K_fLQ9UyVeRVdlV0k',
    appId: '1:153309351632:ios:b36577f9dd057fc62f98d5',
    messagingSenderId: '153309351632',
    projectId: 'todoappflutter-1cff8',
    storageBucket: 'todoappflutter-1cff8.appspot.com',
    iosClientId: '153309351632-6mfv424escs6a99vkc3h65rtdrnmdosv.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjxp9k_yN9ouFcru2SycmFs-pUW-lEOMM',
    appId: '1:153309351632:web:b5de4e18914bd9ae2f98d5',
    messagingSenderId: '153309351632',
    projectId: 'todoappflutter-1cff8',
    authDomain: 'todoappflutter-1cff8.firebaseapp.com',
    storageBucket: 'todoappflutter-1cff8.appspot.com',
    measurementId: 'G-76JSZLF2VY',
  );

}